service: spark-lambdas

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  profile: cif

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /hello/{name}
          method: get
          request:
            parameters:
              paths:
                name: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
